Breakable tiles
dms-akshat/godot_battle_city pull request #20
Opened 2024-04-24 09:09 UTC by CodePokeX

Breakable tilesBreakable tiles for tank to pass through added for tank to pass through added

2024-04-24 17:41 UTC, yukitya-1811 commented
Is there no breakable_tile.gd?

2024-04-24 17:44 UTC, CodePokeX commented
There should be

2024-04-24 17:47 UTC, yukitya-1811 commented
Well, you might have forgotten to git add it. Check once. type `git status` and see if it's in untracked files

2024-04-24 17:48 UTC, yukitya-1811 commented
It's not in the scripts folder. Move it there and then commit and push again

2024-04-24 17:58 UTC, CodePokeX commented
Can I do it by tomorrow morning?

2024-04-24 18:10 UTC, yukitya-1811 requested changes
Check these out

2024-04-24 18:10 UTC, ady-1811 commented on BreakableTiles.gd
> +	print(count)
Remove this print statement or comment it out

2024-04-24 18:10 UTC, ady-1811 commented on BreakableTiles.gd
> +	#tilemap.erase_cell(0,pos)
Remove redundant code, unless it's required for debug purposes. If it is required for debug then comment on how it's important

2024-04-24 18:10 UTC, ady-1811 commented on BreakableTiles.gd
> +	#print(global_position)
Same as previous comments, either delete or explain use in debugging

2024-04-24 18:10 UTC, ady-1811 commented on BreakableTiles.gd
> +		$Sprite2D.show()
Try and rename this Sprite2D to CrackedTile instead of just keeping it as Sprite2D

2024-04-25 13:19 UTC, yukitya-1811 approved these changes

2024-04-25 13:19 UTC, merged